spring.application.name=Marketplace
debug=true
spring.datasource.url=${DB_DEV_URL:jdbc:postgresql://localhost:5432/marketplace_db_dev?currentSchema=public}
spring.datasource.username=${DB_DEV_USER:postgres}
spring.datasource.password=${DB_DEV_PASS:postgres}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.clean-disabled=false

marketplace.fee=0.10

server.address=0.0.0.0

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html