spring.application.name=Marketplace
debug=true
spring.datasource.url=${DB_DEV_URL}
spring.datasource.username=${DB_DEV_USER}
spring.datasource.password=${DB_DEV_PASS}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect