ALTER TABLE skus ADD COLUMN color VARCHAR(20) NOT NULL DEFAULT 'black';
ALTER TABLE skus ADD COLUMN width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE skus ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE skus ADD COLUMN length INTEGER NOT NULL DEFAULT 0;
ALTER TABLE skus ADD COLUMN weight DECIMAL(5, 1) NOT NULL DEFAULT 0;
